;;; Code:
(defun isHexChar (x)
  (or (and (>= x ?0)
           (<= x ?9))
      (or (and (>= x ?a)
               (<= x ?z))
          (or (and (>= x ?A)
                   (<= x ?Z))))))

(defun go-to-hex ()
  (while (not (isHexChar (char-after (point))))
    (forward-char 1)))

(defun parsetlv ()
  (interactive)
  (go-to-hex)
  (forward-char 2)
  (go-to-hex)
  (forward-char 2)
  (go-to-hex)
  (newline-and-indent)
  (setq len (string-to-number (string (char-after (point)) (char-after (+ (point) 1))) 16))
  (forward-char 2)
  (go-to-hex)
  (setq biglen (string-to-number (string (char-after (point)) (char-after(+ (point) 1))) 16))
  (setq len (+ len (* biglen 256)))
  (forward-char 2)
  (go-to-hex)
  (newline-and-indent)
  (while (> len 0)
    (setq len (1- len))
    (forward-char 2)
    (go-to-hex))
  (newline-and-indent)
  (newline-and-indent))
